site_name: Solvis Documentation
site_url: https://gns-science.github.io/solvis
repo_url: https://github.com/GNS-Science/solvis
repo_name: GNS-Science/solvis
# strict: true
watch:
  - solvis
  - docs
nav:
  - Home: index.md
  - Usage: usage.md
  - Installation: installation.md
  - API Reference:
    - solvis:
      - api/solvis/index.md
      - filter:
        - filter: api/filter/index.md
        - parent_fault_id_filter: api/filter/parent_fault_id_filter.md
        - rupture_id_filter: api/filter/rupture_id_filter.md
        - subsection_id_filter: api/filter/subsection_id_filter.md
        - chainable_set_base: api/filter/chainable_set_base.md
      - solution:
        - api/solution/index.md
        - inversion_solution:
          - api/solution/inversion_solution/index.md
          - api/solution/inversion_solution/inversion_solution.md
          - api/solution/inversion_solution/inversion_solution_file.md
          - api/solution/inversion_solution/inversion_solution_model.md
        - fault_system_solution:
          - api/solution/fault_system_solution/index.md
          - api/solution/fault_system_solution/fault_system_solution.md
          - api/solution/fault_system_solution/fault_system_solution_file.md
          - api/solution/fault_system_solution/fault_system_solution_model.md
        - composite_solution: api/solution/composite_solution.md
        - solution participation: api/solution/solution_participation.md
        - dataframe_models: api/solution/dataframe_models.md
        - solution_surfaces_builder: api/solution/solution_surfaces_builder.md
        - typing: api/solution/typing.md
      - config: api/solvis/config.md
      - geometry: api/solvis/geometry.md
      - solvis: api/solvis/solvis.md
  - Development and Contributing:
    - contributing.md
    - Testing: testing.md
  - Addendum:
    - Scripts:
      - scripts.md
      - CLI script: scripts/cli.md
    - Changelog: changelog.md

options:
  merge_init_into_class: true
  group_by_category: true
  show_category_heading: true
  members_order: source
  inherited_members: false

theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    # - navigation.tabs.sticky

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - mkdocs-click
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - tables

plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_if_no_docstring: true
            signature_crossrefs: true
            annotations_path: source
            # show_source: true

            extensions:
            - pydantic: {schema: true}
            - solvis/dochelper/extension.py:DynamicDocstrings:
                object_paths:
                  - solvis.solution.inversion_solution.inversion_solution.InversionSolution
                  - solvis.solution.inversion_solution.inversion_solution_file.InversionSolutionFile
                  - solvis.solution.inversion_solution.inversion_solution_model.InversionSolutionModel
                  - solvis.solution.fault_system_solution.fault_system_solution.FaultSystemSolution
                  - solvis.solution.fault_system_solution.fault_system_solution_file.FaultSystemSolutionFile
                  - solvis.solution.fault_system_solution.fault_system_solution_model.FaultSystemSolutionModel

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GNS-Science/solvis
      name: GitHub
    - icon: material/email
      link: "mailto:nshm@gns.cri.nz"