# Publish package on main branch if it's tagged with 'v*'

name: release & publish workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    tags:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # call-test-workflow:
  #   #https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
  #   uses: ./.github/workflows/run-tests.yml
  #   secrets: inherit

  release:
    name: Create Release
    # needs: call-test-workflow

    # permissions:
    #   id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get version from tag
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Get Changelog Entry
        id: changelog_reader
        uses: GNS-Science/changelog-reader-action@master
        with:
          validation_depth: 10
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md

      # run build using the minimum supported python version
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install and configure Poetry
        uses: GNS-Science/install-poetry@main
        with:
          # version: 1.2.0b3
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Build wheels and source tarball
        run: >-
          poetry build

      - name: show temporary files
        run: >-
          ls -l

      - name: create github release
        id: create_release
        uses: GNS-Science/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{ steps.changelog_reader.outputs.changes }}
          files: dist/*.whl
          draft: false
          prerelease: false

      - name: publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
